title: Raphael Pacheco
logo: https://media.licdn.com/dms/image/D4D35AQHEZINI2H_2sg/profile-framedphoto-shrink_200_200/0/1691686317677?e=1696435200&v=beta&t=WzN0n-FvgmF5BENNobpfXHFl9zuuFRKGjbCzp0aTJoE
#description: text below image
#show_downloads: true
theme: Minima
